if(System.IO.File.Exists("Assets/Scenes/JoystickCubeDemo.unity"))throw new System.Exception("Scene already exists");
var old=UnityEngine.SceneManagement.SceneManager.GetActiveScene();if(old.isDirty)throw new System.Exception("Save current scene first");
var scene=UnityEditor.SceneManagement.EditorSceneManager.NewScene(UnityEditor.SceneManagement.NewSceneSetup.EmptyScene,UnityEditor.SceneManagement.NewSceneMode.Single);
UnityEngine.Material Mat(string name,UnityEngine.Color color){var shader=UnityEngine.Shader.Find("Universal Render Pipeline/Lit");if(shader==null)shader=UnityEngine.Shader.Find("Standard");var m=new UnityEngine.Material(shader);m.color=color;UnityEditor.AssetDatabase.CreateAsset(m,"Assets/JoystickCube/"+name+".mat");return m;}
var floorMat=Mat("Floor",new UnityEngine.Color(.26f,.48f,.53f));var cubeMat=Mat("Cube",new UnityEngine.Color(1,.39f,.26f));var wallMat=Mat("Boundary",new UnityEngine.Color(.65f,.85f,.88f));
UnityEngine.GameObject Box(string name,UnityEngine.Vector3 pos,UnityEngine.Vector3 size,UnityEngine.Material material){var go=UnityEngine.GameObject.CreatePrimitive(UnityEngine.PrimitiveType.Cube);go.name=name;go.transform.position=pos;go.transform.localScale=size;go.GetComponent<UnityEngine.Renderer>().sharedMaterial=material;return go;}
var plane=UnityEngine.GameObject.CreatePrimitive(UnityEngine.PrimitiveType.Plane);plane.name="Plane";plane.transform.localScale=new UnityEngine.Vector3(2,1,2);plane.GetComponent<UnityEngine.Renderer>().sharedMaterial=floorMat;
Box("NorthWall",new UnityEngine.Vector3(0,.5f,10),new UnityEngine.Vector3(20.5f,1,.5f),wallMat);Box("SouthWall",new UnityEngine.Vector3(0,.5f,-10),new UnityEngine.Vector3(20.5f,1,.5f),wallMat);Box("EastWall",new UnityEngine.Vector3(10,.5f,0),new UnityEngine.Vector3(.5f,1,20),wallMat);Box("WestWall",new UnityEngine.Vector3(-10,.5f,0),new UnityEngine.Vector3(.5f,1,20),wallMat);
for(int i=-8;i<=8;i+=2){Box("GridX",new UnityEngine.Vector3(i,.005f,0),new UnityEngine.Vector3(.025f,.008f,19),wallMat).GetComponent<UnityEngine.Collider>().enabled=false;Box("GridZ",new UnityEngine.Vector3(0,.005f,i),new UnityEngine.Vector3(19,.008f,.025f),wallMat).GetComponent<UnityEngine.Collider>().enabled=false;}
var cube=Box("PlayerCube",new UnityEngine.Vector3(0,.6f,0),UnityEngine.Vector3.one,cubeMat);var rb=cube.AddComponent<UnityEngine.Rigidbody>();rb.constraints=UnityEngine.RigidbodyConstraints.FreezeRotation;rb.interpolation=UnityEngine.RigidbodyInterpolation.Interpolate;rb.collisionDetectionMode=UnityEngine.CollisionDetectionMode.Continuous;
var cameraGo=new UnityEngine.GameObject("Main Camera",typeof(UnityEngine.Camera),typeof(UnityEngine.AudioListener));cameraGo.tag="MainCamera";var camera=cameraGo.GetComponent<UnityEngine.Camera>();camera.transform.position=new UnityEngine.Vector3(0,22,-18);camera.transform.LookAt(UnityEngine.Vector3.zero);camera.orthographic=true;camera.orthographicSize=15;camera.clearFlags=UnityEngine.CameraClearFlags.SolidColor;camera.backgroundColor=new UnityEngine.Color(.055f,.11f,.16f);
var light=new UnityEngine.GameObject("Sun",typeof(UnityEngine.Light));light.transform.rotation=UnityEngine.Quaternion.Euler(50,-30,0);light.GetComponent<UnityEngine.Light>().type=UnityEngine.LightType.Directional;light.GetComponent<UnityEngine.Light>().intensity=1.6f;light.GetComponent<UnityEngine.Light>().shadows=UnityEngine.LightShadows.Soft;UnityEngine.RenderSettings.ambientLight=new UnityEngine.Color(.5f,.55f,.6f);
var canvas=new UnityEngine.GameObject("JoystickCanvas",typeof(UnityEngine.Canvas),typeof(UnityEngine.UI.CanvasScaler),typeof(UnityEngine.UI.GraphicRaycaster));canvas.GetComponent<UnityEngine.Canvas>().renderMode=UnityEngine.RenderMode.ScreenSpaceOverlay;var scaler=canvas.GetComponent<UnityEngine.UI.CanvasScaler>();scaler.uiScaleMode=UnityEngine.UI.CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new UnityEngine.Vector2(1440,900);scaler.matchWidthOrHeight=.5f;
var joyGo=(UnityEngine.GameObject)UnityEditor.PrefabUtility.InstantiatePrefab(UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.GameObject>("Assets/Joystick Pack/Prefabs/Fixed Joystick.prefab"),canvas.transform);var rt=(UnityEngine.RectTransform)joyGo.transform;rt.anchorMin=rt.anchorMax=UnityEngine.Vector2.zero;rt.pivot=new UnityEngine.Vector2(.5f,.5f);rt.anchoredPosition=new UnityEngine.Vector2(155,155);rt.sizeDelta=new UnityEngine.Vector2(180,180);var joystick=joyGo.GetComponent<FixedJoystick>();joystick.DeadZone=.08f;UnityEditor.PrefabUtility.RecordPrefabInstancePropertyModifications(joystick);UnityEditor.PrefabUtility.RecordPrefabInstancePropertyModifications(rt);
var mover=cube.AddComponent<HundredHour.JoystickDemo.JoystickCubeMover>();var so=new UnityEditor.SerializedObject(mover);so.FindProperty("joystick").objectReferenceValue=joystick;so.FindProperty("referenceCamera").objectReferenceValue=camera;so.ApplyModifiedPropertiesWithoutUndo();
var textGo=new UnityEngine.GameObject("Instructions",typeof(UnityEngine.RectTransform),typeof(UnityEngine.UI.Text));textGo.transform.SetParent(canvas.transform,false);var tr=(UnityEngine.RectTransform)textGo.transform;tr.anchorMin=tr.anchorMax=tr.pivot=new UnityEngine.Vector2(0,1);tr.anchoredPosition=new UnityEngine.Vector2(45,-30);tr.sizeDelta=new UnityEngine.Vector2(1100,90);var t=textGo.GetComponent<UnityEngine.UI.Text>();t.font=UnityEngine.Resources.GetBuiltinResource<UnityEngine.Font>("LegacyRuntime.ttf");t.fontSize=25;t.color=UnityEngine.Color.white;t.text="JOYSTICK CUBE\nDrag the stick to run. Release to stop.";t.raycastTarget=false;
var es=new UnityEngine.GameObject("EventSystem");es.SetActive(false);es.AddComponent<UnityEngine.EventSystems.EventSystem>();var module=es.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();module.actionsAsset=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.InputSystem.InputActionAsset>("Assets/InputSystem_Actions.inputactions");var refs=UnityEditor.AssetDatabase.LoadAllAssetsAtPath("Assets/InputSystem_Actions.inputactions").OfType<UnityEngine.InputSystem.InputActionReference>().ToArray();module.point=refs.First(r=>r.name=="UI/Point");module.leftClick=refs.First(r=>r.name=="UI/Click");module.move=refs.First(r=>r.name=="UI/Navigate");module.submit=refs.First(r=>r.name=="UI/Submit");module.cancel=refs.First(r=>r.name=="UI/Cancel");es.SetActive(true);
UnityEditor.AssetDatabase.SaveAssets();UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene,"Assets/Scenes/JoystickCubeDemo.unity");return "Built JoystickCubeDemo";
