var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();if(scene.path!="Assets/Scenes/GameScene/NatureStage.unity" || UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Open NatureStage outside Play mode");if(UnityEngine.GameObject.Find("NaturePlayerCube")!=null)throw new System.Exception("NaturePlayerCube already exists");
var cam=UnityEngine.Object.FindObjectsByType<UnityEngine.Camera>(UnityEngine.FindObjectsSortMode.None).First(c=>c.name=="Camera (1)");cam.tag="MainCamera";cam.allowHDR=true;cam.nearClipPlane=.1f;cam.farClipPlane=1000;
var old=cam.GetComponent<LowPolyVegetation_CameraControl>();if(old!=null)old.enabled=false;
var brain=cam.GetComponent<Unity.Cinemachine.CinemachineBrain>();if(brain==null)brain=cam.gameObject.AddComponent<Unity.Cinemachine.CinemachineBrain>();
var mist=cam.GetComponent<MistFilterEffect>();if(mist==null)mist=cam.gameObject.AddComponent<MistFilterEffect>();mist.mistFilterShader=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Shader>("Assets/MistFilter.shader");mist.mistIntensity=.533f;mist.mistBlur=2.75f;mist.highlightBoost=1.82f;mist.softness=.78f;mist.hazeAmount=.079f;mist.blurSpread=1.13f;mist.mistColor=UnityEngine.Color.white;
var terrain=UnityEngine.Terrain.activeTerrain;var position=new UnityEngine.Vector3(-11,0,48);position.y=terrain.SampleHeight(position)+terrain.transform.position.y+.65f;
var cube=UnityEngine.GameObject.CreatePrimitive(UnityEngine.PrimitiveType.Cube);cube.name="NaturePlayerCube";cube.transform.position=position;cube.transform.localScale=new UnityEngine.Vector3(.9f,1.2f,.9f);
var mat=new UnityEngine.Material(UnityEngine.Shader.Find("Standard"));mat.color=new UnityEngine.Color(1,.38f,.18f);mat.SetFloat("_Glossiness",.2f);UnityEditor.AssetDatabase.CreateAsset(mat,"Assets/Scenes/GameScene/NaturePlayerCube.mat");cube.GetComponent<UnityEngine.Renderer>().sharedMaterial=mat;
var rb=cube.AddComponent<UnityEngine.Rigidbody>();rb.constraints=UnityEngine.RigidbodyConstraints.FreezeRotation;rb.interpolation=UnityEngine.RigidbodyInterpolation.Interpolate;rb.collisionDetectionMode=UnityEngine.CollisionDetectionMode.Continuous;
var vgo=new UnityEngine.GameObject("NatureFollowCamera");var vcam=vgo.AddComponent<Unity.Cinemachine.CinemachineCamera>();vcam.Target.TrackingTarget=cube.transform;vcam.Lens.FieldOfView=40;vcam.Lens.NearClipPlane=.1f;vcam.Lens.FarClipPlane=1000;
var follow=vgo.AddComponent<Unity.Cinemachine.CinemachineFollow>();follow.TrackerSettings.BindingMode=Unity.Cinemachine.TargetTracking.BindingMode.WorldSpace;follow.TrackerSettings.PositionDamping=new UnityEngine.Vector3(.6f,.8f,.6f);follow.FollowOffset=new UnityEngine.Vector3(4,3,5);
var aim=vgo.AddComponent<Unity.Cinemachine.CinemachineRotationComposer>();aim.TargetOffset=new UnityEngine.Vector3(0,.35f,0);aim.Damping=new UnityEngine.Vector2(.5f,.5f);aim.Composition.ScreenPosition=new UnityEngine.Vector2(0,.12f);
var canvas=new UnityEngine.GameObject("NatureJoystickCanvas",typeof(UnityEngine.Canvas),typeof(UnityEngine.UI.CanvasScaler),typeof(UnityEngine.UI.GraphicRaycaster));canvas.GetComponent<UnityEngine.Canvas>().renderMode=UnityEngine.RenderMode.ScreenSpaceOverlay;var scaler=canvas.GetComponent<UnityEngine.UI.CanvasScaler>();scaler.uiScaleMode=UnityEngine.UI.CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new UnityEngine.Vector2(1440,900);scaler.matchWidthOrHeight=.5f;
var joyGo=(UnityEngine.GameObject)UnityEditor.PrefabUtility.InstantiatePrefab(UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.GameObject>("Assets/Joystick Pack/Prefabs/Fixed Joystick.prefab"),canvas.transform);var rt=(UnityEngine.RectTransform)joyGo.transform;rt.anchorMin=rt.anchorMax=UnityEngine.Vector2.zero;rt.pivot=new UnityEngine.Vector2(.5f,.5f);rt.anchoredPosition=new UnityEngine.Vector2(155,155);rt.sizeDelta=new UnityEngine.Vector2(180,180);var joy=joyGo.GetComponent<FixedJoystick>();joy.DeadZone=.08f;UnityEditor.PrefabUtility.RecordPrefabInstancePropertyModifications(rt);UnityEditor.PrefabUtility.RecordPrefabInstancePropertyModifications(joy);
var mover=cube.AddComponent<HundredHour.JoystickDemo.JoystickCubeMover>();var so=new UnityEditor.SerializedObject(mover);so.FindProperty("joystick").objectReferenceValue=joy;so.FindProperty("referenceCamera").objectReferenceValue=cam;so.FindProperty("speed").floatValue=3.5f;so.ApplyModifiedPropertiesWithoutUndo();
if(UnityEngine.Object.FindFirstObjectByType<UnityEngine.EventSystems.EventSystem>()==null){var es=new UnityEngine.GameObject("EventSystem");es.SetActive(false);es.AddComponent<UnityEngine.EventSystems.EventSystem>();var module=es.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();module.actionsAsset=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.InputSystem.InputActionAsset>("Assets/InputSystem_Actions.inputactions");var refs=UnityEditor.AssetDatabase.LoadAllAssetsAtPath("Assets/InputSystem_Actions.inputactions").OfType<UnityEngine.InputSystem.InputActionReference>().ToArray();module.point=refs.First(r=>r.name=="UI/Point");module.leftClick=refs.First(r=>r.name=="UI/Click");module.move=refs.First(r=>r.name=="UI/Navigate");module.submit=refs.First(r=>r.name=="UI/Submit");module.cancel=refs.First(r=>r.name=="UI/Cancel");es.SetActive(true);}
UnityEditor.EditorUtility.SetDirty(cam);UnityEditor.EditorUtility.SetDirty(mist);UnityEditor.AssetDatabase.SaveAssets();UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);return new {spawn=position.ToString(),shader=mist.mistFilterShader.isSupported};
