var d=UnityEngine.Object.FindFirstObjectByType<HundredHour.Environments.MansionSignalDirector>();
var t=d.GetType();var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
d.saveEnabled=false;d.useAI=false;d.BeginEncounter();d.Game.State.phase=HundredHour.RealityShow.ShowPhase.Victory;
var results=new System.Collections.Generic.List<string>();
var watch=t.GetMethod("WatchFinale",flags);
int ended=0;
var routine=(System.Collections.IEnumerator)watch.Invoke(d,new object[]{new Func<bool>(()=>false),new Func<float>(()=>UnityEngine.Time.realtimeSinceStartup-31),new Action(()=>ended++)});
if(routine.MoveNext()||ended!=1)throw new Exception("watchdog did not exit");results.Add("PASS stalled voice watchdog");
ended=0;routine=(System.Collections.IEnumerator)watch.Invoke(d,new object[]{new Func<bool>(()=>true),new Func<float>(()=>0),new Action(()=>ended++)});
if(routine.MoveNext()||ended!=0)throw new Exception("finished watchdog repeated");results.Add("PASS finished watchdog no duplicate");
var old=HundredHour.Localization.GameLanguage.Current;HundredHour.Localization.GameLanguage.Select(HundredHour.Localization.GameLocale.English,false);
t.GetMethod("GenerateFinaleEpilogue",flags).Invoke(d,new object[]{d.content.Person("yuto"),"",new Action(()=>ended++)});
var ep=(string)t.GetField("finaleEpilogue",flags).GetValue(d);if(HundredHour.Localization.GameLanguage.ContainsJapanese(ep.Replace(d.content.Person("yuto").displayName,"")))throw new Exception(ep);results.Add("PASS English offline epilogue");
d.useAI=true;
t.GetMethod("PlayFinaleThenStaffRoll",flags).Invoke(d,null);
var session=UnityEngine.Object.FindFirstObjectByType<HundredHour.LiveInterview.LiveVoiceSession>();
if(session)session.Disconnect();
var options=(string[])d.view.GetType().GetField("pendingOptions",flags).GetValue(d.view);if(options.Length!=1||options[0]!="Continue to credits")throw new Exception("no exit choice");results.Add("PASS visible exit during connection");
if(session)session.GetType().GetMethod("Handle",flags).Invoke(session,new object[]{Newtonsoft.Json.Linq.JObject.Parse("{\"type\":\"live.text\",\"role\":\"assistant\",\"delta\":\"I'm happy we're here together.\"}")});
if(!d.view.body.text.Contains("happy"))throw new Exception("no subtitles");results.Add("PASS partner subtitles");
d.useAI=false;d.Choose(0);
var roll=d.view.GetType().GetField("staffRoll",flags).GetValue(d.view) as UnityEngine.GameObject;
if(!roll||!roll.activeInHierarchy)throw new Exception("skip did not reach credits");results.Add("PASS manual exit reaches credits");
d.Choose(0);results.Add("PASS duplicate finish harmless");
HundredHour.Localization.GameLanguage.Select(old,false);
System.IO.File.WriteAllText("Temp/FinalePlayVerification.txt",string.Join("\n",results));return string.Join("\n",results);
