if(GameObject.Find("ChatTestRoot")!=null)throw new System.Exception("ChatTestRoot already exists");
var font=AssetDatabase.LoadAssetAtPath<Font>("Assets/UI/AuditionHeader/Fonts/NotoSansCJKjp-Regular.otf");
RectTransform Rect(string name,Transform parent,float x,float y,float w,float h){var r=(RectTransform)new GameObject(name,typeof(RectTransform)).transform;r.SetParent(parent,false);r.anchorMin=r.anchorMax=r.pivot=new Vector2(.5f,.5f);r.anchoredPosition=new Vector2(x,y);r.sizeDelta=new Vector2(w,h);return r;}
UnityEngine.UI.Text Label(string name,Transform parent,string value,float x,float y,float w,float h,int size){var r=Rect(name,parent,x,y,w,h);var t=r.gameObject.AddComponent<UnityEngine.UI.Text>();t.font=font;t.fontSize=size;t.text=value;t.color=new Color(.08f,.23f,.34f);t.raycastTarget=false;t.alignment=TextAnchor.MiddleLeft;return t;}
var canvas=UnityEngine.Object.FindFirstObjectByType<Canvas>();if(canvas==null){var go=new GameObject("ChatTestCanvas",typeof(Canvas),typeof(UnityEngine.UI.CanvasScaler),typeof(UnityEngine.UI.GraphicRaycaster));canvas=go.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var scaler=go.GetComponent<UnityEngine.UI.CanvasScaler>();scaler.uiScaleMode=UnityEngine.UI.CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(1440,900);scaler.matchWidthOrHeight=.5f;}
var panel=Rect("ChatTestPanel",canvas.transform,0,0,1080,650);var bg=panel.gameObject.AddComponent<HundredHour.UI.Audition.GlassSurfaceGraphic>();bg.SetStyle(new Color(.95f,.99f,1,.98f),new Color(.78f,.92f,.97f,.98f),Color.white,30);bg.raycastTarget=false;
Label("Title",panel,"PythonAPI · Unity Chat Test",-10,245,960,70,32);
Label("Endpoint",panel,"127.0.0.1:8001  /  api/chat",-10,190,960,36,18);
var inputRect=Rect("MessageInput",panel,-90,105,800,80);var inputBg=inputRect.gameObject.AddComponent<UnityEngine.UI.Image>();inputBg.color=Color.white;
var inputText=Label("Text",inputRect,"",0,0,760,70,24);var placeholder=Label("Placeholder",inputRect,"メッセージを入力",0,0,760,70,24);placeholder.color=new Color(.4f,.5f,.6f);
var input=inputRect.gameObject.AddComponent<UnityEngine.UI.InputField>();input.textComponent=inputText;input.placeholder=placeholder;input.lineType=UnityEngine.UI.InputField.LineType.SingleLine;input.targetGraphic=inputBg;
var br=Rect("SendButton",panel,410,105,160,80);var bi=br.gameObject.AddComponent<UnityEngine.UI.Image>();bi.color=new Color(1,.62f,.55f);var button=br.gameObject.AddComponent<UnityEngine.UI.Button>();button.targetGraphic=bi;var bt=Label("Label",br,"送信",0,0,150,70,24);bt.alignment=TextAnchor.MiddleCenter;
var result=Label("ResultText",panel,"応答待ち",0,-110,960,300,25);result.alignment=TextAnchor.UpperLeft;result.horizontalOverflow=HorizontalWrapMode.Wrap;
var root=new GameObject("ChatTestRoot");root.SetActive(false);var api=root.AddComponent<HundredHour.AIChat.ChatApiClient>();var view=root.AddComponent<HundredHour.AIChat.ChatDemoView>();var controller=root.AddComponent<HundredHour.AIChat.ChatDemoController>();
void Ref(UnityEngine.Object obj,string field,UnityEngine.Object value){var so=new SerializedObject(obj);so.FindProperty(field).objectReferenceValue=value;so.ApplyModifiedPropertiesWithoutUndo();}
Ref(view,"messageInput",input);Ref(view,"sendButton",button);Ref(view,"resultText",result);Ref(controller,"apiClient",api);root.SetActive(true);
if(UnityEngine.Object.FindFirstObjectByType<UnityEngine.EventSystems.EventSystem>()==null){var es=new GameObject("EventSystem");es.SetActive(false);es.AddComponent<UnityEngine.EventSystems.EventSystem>();var module=es.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();module.actionsAsset=AssetDatabase.LoadAssetAtPath<UnityEngine.InputSystem.InputActionAsset>("Assets/InputSystem_Actions.inputactions");var refs=AssetDatabase.LoadAllAssetsAtPath("Assets/InputSystem_Actions.inputactions").OfType<UnityEngine.InputSystem.InputActionReference>().ToArray();module.point=refs.First(r=>r.name=="UI/Point");module.leftClick=refs.First(r=>r.name=="UI/Click");module.move=refs.First(r=>r.name=="UI/Navigate");module.submit=refs.First(r=>r.name=="UI/Submit");module.cancel=refs.First(r=>r.name=="UI/Cancel");es.SetActive(true);}
return "ChatTest UI created and references assigned";
