System.Collections.IEnumerator Verify(){
var player=UnityEngine.Object.FindFirstObjectByType<HundredHour.Cutscenes.CutscenePlayer>();var ids=player.GetActors().Keys.ToArray();var failures=new System.Collections.Generic.List<string>();
void Require(bool value,string reason){if(!value)failures.Add(reason);}
Require(HundredHour.Cutscenes.CameraShotSolver.ZoomFov(40,25,.5f)<40,"zoom-in interpolation");Require(HundredHour.Cutscenes.CameraShotSolver.ZoomFov(25,50,.5f)>25,"zoom-out interpolation");
try{HundredHour.Cutscenes.PythonCameraPlanSource.Parse("{\"shots\":[]}",ids);failures.Add("empty plan accepted");}catch(System.ArgumentException){}
try{HundredHour.Cutscenes.PythonCameraPlanSource.Parse("{\"shots\":[{\"actorA\":\"UNKNOWN\"}]}",ids);failures.Add("unknown actor accepted");}catch(System.ArgumentException){}
var mover=player.suspendDuringPlayback[0];var body=player.actors[0].GetComponent<UnityEngine.Rigidbody>();bool initialMover=mover.enabled,initialKinematic=body.isKinematic;var start=body.position;int finished=0;System.Action handler=()=>finished++;player.Finished+=handler;var seen=new System.Collections.Generic.HashSet<int>();bool partialFade=false;float zoomInMin=90,zoomInMax=0,zoomOutMin=90,zoomOutMax=0;
try{
player.PlayDefault();float deadline=UnityEngine.Time.realtimeSinceStartup+75;
while(player.IsPlaying && UnityEngine.Time.realtimeSinceStartup<deadline){yield return new UnityEngine.WaitForEndOfFrame();partialFade|=player.FadeAlpha>.05f&&player.FadeAlpha<.95f;if(!player.IsShotActive)continue;Require(!mover.enabled&&body.isKinematic,"controls not suspended");var vc=player.GetComponentInChildren<Unity.Cinemachine.CinemachineCamera>();if(player.CurrentShot==4){zoomInMin=UnityEngine.Mathf.Min(zoomInMin,vc.Lens.FieldOfView);zoomInMax=UnityEngine.Mathf.Max(zoomInMax,vc.Lens.FieldOfView);}if(player.CurrentShot==5){zoomOutMin=UnityEngine.Mathf.Min(zoomOutMin,vc.Lens.FieldOfView);zoomOutMax=UnityEngine.Mathf.Max(zoomOutMax,vc.Lens.FieldOfView);}if(player.ShotProgress>.35f&&seen.Add(player.CurrentShot))UnityEngine.ScreenCapture.CaptureScreenshot("Screenshots/CutsceneShot"+player.CurrentShot+".png");}
Require(!player.IsPlaying,"sequence timeout");Require(seen.Count==7,"not all shots rendered");Require(partialFade,"no partial fade");Require(zoomInMax-zoomInMin>10&&zoomOutMax-zoomOutMin>20,"lens zoom did not progress");Require(mover.enabled==initialMover&&body.isKinematic==initialKinematic,"completion restore");Require(player.hideDuringPlayback.All(g=>g.activeSelf),"hidden UI not restored");Require(finished==1,"completion event count");
yield return new UnityEngine.WaitForSecondsRealtime(2.5f);Require(player.outputCamera.GetComponent<Unity.Cinemachine.CinemachineBrain>().ActiveVirtualCamera.Name=="NatureFollowCamera","game camera not restored");
player.PlayDefault();yield return new UnityEngine.WaitForSecondsRealtime(.8f);player.Stop();Require(!player.IsPlaying&&mover.enabled==initialMover&&body.isKinematic==initialKinematic,"manual stop restore");
player.PlayDefault();yield return new UnityEngine.WaitForSecondsRealtime(.8f);player.enabled=false;Require(!player.IsPlaying&&mover.enabled==initialMover,"disable restore");player.enabled=true;
var generated=UnityEditor.AssetDatabase.LoadAssetAtPath<HundredHour.Cutscenes.CutsceneSequence>("Assets/Cutscenes/Sequences/NaturalLanguageExample.asset");var fast=UnityEngine.Object.Instantiate(generated);foreach(var s in fast.shots){s.duration=.3f;s.transitionSeconds=.1f;}fast.fadeIn=fast.fadeOut=.1f;player.Play(fast);yield return new UnityEngine.WaitForSecondsRealtime(3);Require(!player.IsPlaying,"generated plan playback");UnityEngine.Object.Destroy(fast);
}finally{player.Stop();player.enabled=true;player.Finished-=handler;System.IO.File.WriteAllText("Temp/CutsceneVerification.txt","pass="+(failures.Count==0)+"\nshots="+seen.Count+"\npartialFade="+partialFade+"\nzoomIn="+zoomInMin+".."+zoomInMax+"\nzoomOut="+zoomOutMin+".."+zoomOutMax+"\n"+string.Join("\n",failures.Distinct()));}}
UnityEngine.EventSystems.EventSystem.current.StartCoroutine(Verify());return "Verifying seven-shot playback, zoom, fades, stop, disable and generated plan";
